name: rapid-saas-shared-platform

services:
  validation:
    build:
      context: .

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  ingress:
    image: nginx:1.27-alpine
    ports:
      - "8090:8080"
    volumes:
      - ./ingress/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
