-- TiltGuard MVP schema for SQLite/libSQL/Turso.
-- ULIDs are generated by application code; timestamps are UTC epoch millis.

CREATE TABLE IF NOT EXISTS tenants (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    api_key_hash TEXT NOT NULL,
    region TEXT NOT NULL DEFAULT 'lhr',
    plan TEXT NOT NULL DEFAULT 'starter',
    created_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    visit_token TEXT NOT NULL,
    account_id TEXT,
    event_type TEXT NOT NULL CHECK (event_type IN ('signup', 'login', 'deposit', 'custom')),
    device_id TEXT NOT NULL,
    cluster_id TEXT,
    fingerprint_hash TEXT NOT NULL,
    minhash BLOB NOT NULL,
    simhash INTEGER NOT NULL,
    ip TEXT NOT NULL,
    asn INTEGER,
    country TEXT,
    ja3 TEXT,
    ja4 TEXT,
    user_agent TEXT,
    score INTEGER CHECK (score BETWEEN 0 AND 100),
    recommendation TEXT CHECK (recommendation IN ('allow', 'review', 'deny')),
    reason_codes TEXT,
    created_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_events_tenant_created ON events(tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_device ON events(tenant_id, device_id);
CREATE INDEX IF NOT EXISTS idx_events_account ON events(tenant_id, account_id);
CREATE INDEX IF NOT EXISTS idx_events_cluster ON events(tenant_id, cluster_id);

CREATE TABLE IF NOT EXISTS fingerprints (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    fingerprint_hash TEXT NOT NULL,
    canvas_hash TEXT,
    webgl_hash TEXT,
    audio_hash TEXT,
    fonts_minhash BLOB,
    first_seen INTEGER NOT NULL,
    last_seen INTEGER NOT NULL,
    seen_count INTEGER NOT NULL DEFAULT 1,
    UNIQUE (tenant_id, fingerprint_hash)
);

CREATE TABLE IF NOT EXISTS devices (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    cluster_id TEXT,
    fingerprint_id TEXT,
    first_seen INTEGER NOT NULL,
    last_seen INTEGER NOT NULL,
    seen_count INTEGER NOT NULL DEFAULT 1,
    fingerprint_hash TEXT NOT NULL,
    canvas_hash TEXT,
    webgl_hash TEXT,
    audio_hash TEXT,
    fonts_minhash BLOB,
    UNIQUE(tenant_id, fingerprint_hash)
);

CREATE TABLE IF NOT EXISTS accounts (
    id TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    cluster_id TEXT,
    devices_count INTEGER DEFAULT 0,
    risk_max INTEGER DEFAULT 0,
    flagged_at INTEGER,
    PRIMARY KEY (tenant_id, id)
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS clusters (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    account_count INTEGER NOT NULL DEFAULT 0,
    device_count INTEGER NOT NULL DEFAULT 0,
    risk_max INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'reviewed', 'suppressed')),
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_clusters_tenant_risk ON clusters(tenant_id, risk_max DESC, updated_at DESC);

CREATE TABLE IF NOT EXISTS links (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    source_account_id TEXT NOT NULL,
    target_account_id TEXT NOT NULL,
    via TEXT NOT NULL,
    confidence REAL NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    evidence TEXT,
    created_at INTEGER NOT NULL,
    UNIQUE(tenant_id, source_account_id, target_account_id, via)
);
CREATE INDEX IF NOT EXISTS idx_links_source ON links(tenant_id, source_account_id);

CREATE TABLE IF NOT EXISTS minhash_bands (
    tenant_id TEXT NOT NULL,
    band_idx INTEGER NOT NULL,
    band_hash INTEGER NOT NULL,
    device_id TEXT NOT NULL,
    PRIMARY KEY (tenant_id, band_idx, band_hash, device_id)
);

CREATE TABLE IF NOT EXISTS reason_codes (
    code TEXT PRIMARY KEY,
    severity INTEGER NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS customer_rules (
    tenant_id TEXT NOT NULL,
    name TEXT NOT NULL,
    rule_json TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS feedback (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    event_id TEXT,
    account_id TEXT,
    label TEXT NOT NULL CHECK (label IN ('fraud', 'not_fraud', 'unknown')),
    note TEXT,
    created_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS webhook_deliveries (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    url TEXT NOT NULL,
    payload TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_status INTEGER,
    next_attempt_at INTEGER,
    delivered_at INTEGER
);
